apiVersion: v1
kind: Service
metadata:
  name: db-service-declarative
spec:
  selector:
    app: db-declarative
  ports:
    - protocol: 'TCP'
      port: 27017
      targetPort: 27017
  type: LoadBalancer