apiVersion: v1
kind: Service
metadata:
  name: backend-service-declarative
spec:
  selector:
    app: backend-declarative
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  type: LoadBalancer