apiVersion: v1
kind: Service
metadata:
  name: frontend-service-declarative
spec:
  selector:
    app: frontend-declarative
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  type: LoadBalancer