apiVersion: v1
kind: PersistentVolume
metadata:
  name: mo-backend-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /data/standard/default/mo-backend-pv
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem