apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mo-backend-pvc
spec:
  volumeName: mo-backend-pv
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi